### ISSUE TITLE
best practice for config

### ISSUE THREAD

**Issue by ghost** [workmanw/ember-did-change-attrs#16]
First off, thanks for publishing this addon. I think it addresses uses within production ember applications.
We use the ember eslint addon in our app.
[This rule](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/avoid-leaking-state-in-ember-objects.md#avoid-leaking-state) complains about the following snippet:
```javascript
 didChangeAttrsConfig: {
    attrs: ['email']
  }
```
Does the leaking state apply here within components? Or should we revise the API?

**Comment by alexlafroscia** [comment]
The leaking state issue doesn't apply here. The rule is trying to warn against something like this:

```javascript
const Foo = Ember.Object.extend({
  values: ['foo']
});

const first = Foo.create();
foo.get('values').push('bar');

const second = Foo.create();
```

What's the value of `second.get('values')`? It's actually `['foo', 'bar']` because under the hood, both objects are sharing a single instance of the `values` array. This is almost always _not_ what the user wanted and probably not what they would expect, so the lint rule warns against having anything as a property that isn't a primitive.

However, in this case, as long as you're not modifying `didChangeAttrsConfig` at runtime somewhere, it's not actually a problem.

The `eslint` rule has the ability to whitelist additional keys that are "safe", so maybe there should be a recommendation in the README about configuring that. Better yet, a codemod on installation that does it automatically (although that's quite a bit more complicated).

**Comment by ghost** [comment]
Thanks for the update @alexlafroscia . I understand the main issue with leaky state. In this case, wouldn't runtime modifications to `didChangeAttrsConfig` still cause the same kind of problem as your example?
As for a fix, I think better documentation on how to configure this for your project would be great. I think code mods are overkill for this particular case as there could be too many examples of snippets that trigger the rule.

**Comment by alexlafroscia** [comment]
Oh yeah, it totally would. I'm just saying that you shouldn't be changing `didChangeAttrsConfig` at runtime anyway, so it's probably a non-issue for this addon.

**Comment by ghost** [comment]
ah, cool, makes sense.
